# Generated by Django 3.2.3 on 2022-05-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='souscategory_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.souscategorie'),
        ),
    ]
