# Generated by Django 3.2.3 on 2022-05-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20220515_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='souscategory_id',
            new_name='souscategory',
        ),
    ]
