# Generated by Django 3.2.3 on 2022-05-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20220515_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategorie',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='souscategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.souscategorie'),
        ),
    ]
