# Generated by Django 3.2.3 on 2022-05-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='aftercat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.aftercat'),
        ),
    ]
