# Generated by Django 3.2.3 on 2022-05-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20220516_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='aftercat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.aftercat'),
        ),
        migrations.AddField(
            model_name='produit',
            name='reduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='poid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.poid'),
        ),
    ]
