# Generated by Django 3.2.3 on 2022-05-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20220525_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='ville',
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Pour expedition', 'Pour expedition'), ('Complete', 'Complete')], default='En attente', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ville',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.region'),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.order')),
                ('produit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.produit')),
            ],
        ),
    ]
