# Generated by Django 3.2.3 on 2022-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20220525_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='desc1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='desc2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='desc3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='desc4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='fulldesc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
